version: "3.7"

services:
  sonarqube:
    image: sonarqube:latest
    volumes:
      - vol-sonarqube-data:/opt/sonarqube/data
      - vol-sonarqube-extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"

volumes:
  vol-sonarqube-data:
  vol-sonarqube-extensions:
